# Generated by Django 2.2.10 on 2020-09-07 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_wished', to='auctions.Listing')),
                ('wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_wished', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
