# Generated by Django 2.2.10 on 2020-09-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200907_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Collectibles', 'Collectibles'), ('Games & Toys', 'Games & Toys'), ('Motor Vehicle', 'Motor Vehicle'), ('Property', 'Property'), ('None', 'None')], default='NONE', max_length=20),
        ),
    ]
