# Generated by Django 2.2.10 on 2020-09-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200918_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='commentor',
        ),
    ]
